### ISSUE TITLE
RDF/XML vs OWL/XML file format

### ISSUE THREAD

**Issue by 11235813** [G-Node/neuro-ontology#2]
Protégé seems to change the syntax of the RDF/XML file at random, for example, when reopening the file. The semantics of the file are not affected. This change in syntax causes difference between the last commit and the local current version of the file.

An alternative would be to save the ontology as an OWL/XML file. As observed, its syntax is not modified unless the ontology is semantically modified.

**Comment by macroteck** [comment]
Thanks for this info
